pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
		
		stage('Checkout') {
            steps {
                checkout scm
            }
        }

		stage('Compile') {
				steps {
					sh 'mkdir -p build'
					sh 'javac -d build HelloWorld/src/HelloWorld.java'
				}
			}

		stage('Run') {
				steps {
					sh 'java -cp build HelloWorld'
				}
			}
		}
}
