pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World 2'
            }
        }
		
		stage('Checkout') {
            steps {
                checkout scm
            }
        }

		stage('Compile') {
				steps {
					sh 'mkdir -p build'
					sh 'javac -d build src/Hello.java'
				}
			}

		stage('Run') {
				steps {
					sh 'java -cp build Hello'
				}
			}
		}
}
