pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
		
		stage('Checkout') {
            steps {
                checkout scm
            }
        }

		stage('Compile') {
				steps {
					sh 'mkdir -p build'
					sh 'javac -d build HelloWorld/src/HelloWorld.java'
				}
			}

		stage('Run') {
				steps {
					sh 'java -cp build HelloWorld'
				}
			}
			
		stage('Create JAR') {
            steps {
                sh '''
                    mkdir -p dist
                    echo "Main-Class: HelloWorld" > manifest.txt
                    jar cfm dist/helloworld.jar manifest.txt -C build .
                '''
            }
        }

        stage('Run JAR') {
            steps {
                sh 'java -jar dist/helloworld.jar'
            }
        }
		
	}
}
